baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Guilherme Duarte"
theme = "hugo-bootstrap-premium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/duarteguilherme"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/guilhermejd1"

[params]
    description = "Este é o blog onde posto textos relacionados a Metodologia, Ciência de Dados, Política, Direito, Música, entre outros temas."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

